# Generated by Django 3.1.4 on 2021-01-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20210106_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.FileField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
