# Generated by Django 3.1.4 on 2021-01-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20210106_0725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='reg_fee',
            new_name='registration_fee',
        ),
        migrations.AddField(
            model_name='event',
            name='prize_amount',
            field=models.IntegerField(default=1000),
        ),
    ]
