# Generated by Django 3.1.4 on 2021-01-05 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20210105_1049'),
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='registered_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='events.event'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='branch',
            field=models.CharField(choices=[('CSE', 'Computer Science Engineering'), ('ECE', 'Elelctronics and Communication'), ('EEE', 'Electrical Engineering'), ('MECH', 'Mechanical Engineering'), ('CIVIL', 'Civil Engineering'), ('IT', 'Information Technology'), ('AUTO', 'Automobile Engineering'), ('CHM', 'Chemical Engineering')], max_length=50),
        ),
    ]
