# Generated by Django 3.1.4 on 2021-01-06 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_auto_20210105_1049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='branch',
            new_name='department',
        ),
    ]
